import { getAuthConfig, type Env } from './auth';
import { createChromeBrowserClient } from './chrome-client';

export type { Env } from './auth';
export type {
  Action,
  ElementInfo,
  ExecutableStatus,
  FindAndActResult,
  FindAndClickOptions,
  FindAndSelectOptions,
  FindAndTypeOptions,
  FindBySelectorOptions,
  FindByRoleOptions,
  FindByLabelOptions,
  FindByTextOptions,
  FindQuery,
  FindResult,
  FindInteractiveElementOptions,
  GridRange,
  LabelsOverviewOptions,
  ZoneLabelsOptions,
  ZoneLabelsResult,
  WaitStrategyOptions,
  ScanZonesOptions,
  GridCoordinateSpace,
  NavigationWaitOptions,
  PageLoadState,
  LabelsOptions,
  LaunchOptions,
  LaunchResult,
  SelectorWaitState,
  UiInteractiveElement,
  UiLabelsResult,
  UiLayoutRegion,
  UiOverviewRegion,
  UiOverviewResult,
  UiPointOfInterest,
  TabInfo,
  Zone,
  ZoneResult,
} from './chrome-client';

export type {
  Target,
  TargetBySelector,
  TargetByRole,
  TargetByLabel,
  TargetByText,
  TargetByPoint,
  Verify,
  VerifyUrlContains,
  VerifyUrlMatches,
  VerifyTextAppears,
  VerifySelectorGone,
  VerifySelectorAppears,
  VerifyAriaState,
  VerifyCustom,
  Resilience,
  RetryDelayStrategy,
  RetryDelayFixed,
  RetryDelayLinear,
  RetryDelayExponential,
  ActionResult,
  ActionFindResult,
  VerificationResult,
  ActionError,
  ErrorTier,
  ErrorCode,
  AtomicClickOptions,
  AtomicTypeOptions,
  AtomicSelectOptions,
  AtomicSubmitOptions,
} from './resilience-types';

export default function main(env: Env = {}) {
  const config = getAuthConfig(env);
  return createChromeBrowserClient(config);
}
